[package]
name = "camera-tools"
version = "0.0.0"

[build-dependencies]
tauri-build = "1.1"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = "1.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
